### ISSUE TITLE
Soporte de idiomas

### ISSUE THREAD

**Issue by jorgevrgs** [mailrelay/prestashop#1]
Algunos idiomas son diferentes a los que inicialmente espera el sistema en la línea:

https://github.com/mailrelay/prestashop/blob/master/AdminMailRelay.php#L357

Esto debe ser validado ya que sino genera un error fatal, por ejemplo 'cb' es la traducción usada por Prestashop para español Colombia en lugar de 'co'.

**Comment by fernandomm** [comment]
¿Puedes indicar el error que ocurre y el stack trace completo?

Hemos comprobado la última versión del plugin con una instalación del Prestashop que utiliza español de Colombia y el plugin ha funcionado correctamente.
